### ISSUE TITLE
[BUG] Blocks not regenerating

### ISSUE THREAD

**Issue by Aimbot1111** [toppev/strikepractice-public#1]
**Describe the bug**
Some of the less popular blocks don't regenerate properly - eg. stripped wood, lodestones meaning that 10-40% of certain type of block dissappears after the fight. After the given percentage dissappears, you have to restart the server in order to fix certain arena. Oddly enough always the same blocks dissapear no matter what you do. 

**To Reproduce**
1. Create arena with a lot of stripped wood and/or lodestones
2. Fight one time on it
3. Enter the same arena by /arena teleport and some blocks should be gone 

**Expected behavior**
All types of blocks should regenerate properly based on main arenas world. 

**Screenshots**
I don't think that they are needed but I can record whole fight with the blocks disappearing after it if required. 

**Errors and console logs**
I haven't encountered any console logs or errors

**Checklist**
- [ yes ] The issue occurs on latest version of StrikePractice.
- [ It occurs both with and without unofficial addon, I don't use anything which could have cause wrong chunks regeneration like multiverse, worldedit, or worldguard] The issue occurs without other plugins (or non-official addons).
- [ yes ] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [ yes ] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:**
 - Server version: 1.17.1
 - Client version: 1.16.5/1.17.1

**Other plugins**
Newest viaversion&viabackwards (only ones which could have possibly cause this) 

**Additional context**
I have build-in-arenas-world on false and, turning void worlds and expermental block updating on and off didn't help. I don't have enough time to find all blocks which don't regenerate so i only mentioned those.

**Comment by toppev** [comment]
How did you interact with those blocks in the fight? Did you place them, break them, click them or place blocks on top of them or? I'll be testing this later, hopefully soonish.

**Comment by Aimbot1111** [comment]
You don't need to interact with these blocks in any way for them to disappear. They are just a part of the arena

**Comment by toppev** [comment]
Are you sure you teleported to the exact same location? If nothing touches any blocks (break, build on them, water, explosions etc or simply not a build fight) the plugin will not do anything to those blocks, it only regenerates what has been interacted with in the fight.

**Comment by Aimbot1111** [comment]
I did some tests with explosives and this happened... I am not even sure if it's the same bug or not even cause before no explosives were needed for same thing to happen

https://user-images.githubusercontent.com/86470291/160287280-8b221cfd-10ab-47f6-ab8d-e0e5bc9aeb1b.mp4

.

**Comment by toppev** [comment]
Please enable "/sprac debug", it should log information about that explosion and "/arena alerts" to see when arena resets. It could be something different in that server version compared to 1.8 for example.
