### ISSUE TITLE
[BUG] PvP Bots Dont Work

### ISSUE THREAD

**Issue by AsisRekt** [toppev/strikepractice-public#11]
The bug:
PVP bots dont give hits but just follow you.

**To Reproduce**
1. Go to 'Fight a bot' 
2. Select any level
3. Select an arena
4. And then, the bots just won't hit you.

**Expected behavior**
The bots should hit you, but they don't for some reason, and I can't find any solution.

**Errors and console logs**
Could'n find any error in console about it.

**Checklist**
- [yep ] The issue occurs on latest version of StrikePractice.
- [probably, because citizens doesn't give any error ] The issue occurs without other plugins (or non-official addons).
- [yep ] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [yep ] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:**
 - Server version [1.8.8 - 1.15.2 paper spigot]
 - Client version [lunar client 1.8.9]
 - Other version [1.8.8 to 1.15.2]

**Other plugins**
StrikePractice, StrikeAPI
ViaVesions, ViaRewind,ViaBackwards, EssentialsX, EssentialsXChat, NoHunger, Multi-Verse, WorldEdit, VoidGen, PlaceholderAPI, Luckperms, Vault. 

All of them are installed on the latest version!!
Please Help me with it! Thank You!

**Comment by toppev** [comment]
I believe this is either because of a custom spigot or some other plugin cancelling the damage. The test server and many other servers use 1.8.8 paper/spigot and the bots work just fine.

Feel free to re-open this if more information is available.
