### ISSUE TITLE
[BUG] Fight end message send sequence

### ISSUE THREAD

**Issue by Yurinann** [toppev/strikepractice-public#13]
**Describe the bug**
Sometimes message sequence not normal when a fight ends.

**To Reproduce**
1. Start a fight
2. fight end
3. display the message

**Expected behavior**
all messages look like normal.

**Screenshots**
Normal:
![image](https://user-images.githubusercontent.com/75569395/212461256-1bab9324-bf46-4fac-8c27-1e01d2a501a2.png)

Bug:
![image](https://user-images.githubusercontent.com/75569395/212461282-a387e554-e5c7-4c4e-8d5f-ecd2449fa82b.png)

**Errors and console logs**
none

**Checklist**
- [ * ] The issue occurs on latest version of StrikePractice.
- [ * ] The issue occurs without other plugins (or non-official addons).
- [ * ] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [ * ] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:**
 - Server version: ImanitySpigot 2022.11.1 LTS BUILD 3
 - Client version: 1.8.9 Forge+Optifine+LiteLoader
 - Other version: Sprac 3.7.0

**Other plugins**
ImanityPracticeAddon, ViaVersion, ViaRewind, ViaRewind-legacy-support, ...

**Additional context**
none

**Comment by toppev** [comment]
That is 1.8.8 spigot, right? Did you try if that happens on regular spigot or paper (not a fork)? And how often does it happen?

**Comment by toppev** [comment]
Oh nvm, it happens because some parts are sent separately which may cause that. Will look into fixing it.

**Comment by toppev** [comment]
> Hello, I wonder if I can try a latest build version? (I find the dev-build bot in discord but i didn't find a way to download it)

The devbuilds are no longer available. I will most likely update this to spigot within 1 week, most likely next weekend if not before.

I'll close this issue as the problem has been fixed in the code now

**Comment by Yurinann** [comment]
> > Hello, I wonder if I can try a latest build version? (I find the dev-build bot in discord but i didn't find a way to download it)
> 
> The devbuilds are no longer available. I will most likely update this to spigot within 1 week, most likely next weekend if not before.
> 
> I'll close this issue as the problem has been fixed in the code now

@toppev and this issue not only happens in fight-end message
it also in some messages that use more lines
like this:
```
  countdown-go: |
    \n
    &8&m----------------------------
    &b&lReunion &8| &f<kit>
    \n
    &7对手 &f<opponent> &8| &7地图 &f<arena>
    \n
    &b&l战斗开始!
    &8&m----------------------------
```

I set this from one line to more lines, and it sometimes will be disorganized.
