### ISSUE TITLE
[BUG] Deathcountdown not work and will receive "countdown-go" all times when death-countdown set to true

### ISSUE THREAD

**Issue by Yurinann** [toppev/strikepractice-public#14]
**Describe the bug**
/battlekit deathcountdown <kitName> not work
when death-countdown set to true, countdown-go message will displayed all times when respawn

**To Reproduce**
1. Create a custom kit and use /battlekit bedwars
2. Do `/battlekit deathcountdown <kitName>`
3. Then have a test or restart to have a test
4. it cannot work, and each respawn will receive the message like the issue's title

**Expected behavior**
1. when deathcountdown set to true, respawn can have time
2. each respawn don't receive countdown-go message like normal mode
(and if countdown-go message is for all, i think can have two message settings: `fight-countdown-go` message and `death-countdown-go` message)

**Screenshots**
none

**Errors and console logs**
Debug:
```
[16:37:16 INFO]: [SP DEBUG] #respawn Therlly called (bedwars or similar)
[16:37:16 INFO]: [SP DEBUG] #respawn Kiyotsuki called (bedwars or similar)
[16:37:16 INFO]: [SP DEBUG] colorable item detected: WOOL (0)
[16:37:16 INFO]: [SP DEBUG] double damage event detected and ignored, diff: 300 ms
[16:37:17 INFO]: [SP DEBUG] colorable item detected: WOOL (0)
[16:37:17 INFO]: [SP DEBUG] Therlly will not receive message countdown-go because it's empty or 'false'
[16:37:17 INFO]: [SP DEBUG] double damage event detected and ignored, diff: 50 ms
[16:37:17 INFO]: [SP DEBUG] Kiyotsuki will not receive message countdown-go because it's empty or 'false' // but also can receive it
```

**Checklist**
- [ * ] The issue occurs on latest version of StrikePractice.
- [ * ] The issue occurs without other plugins (or non-official addons).
- [ * ] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [ * ] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:**
 - Server version ImanitySpigot 2022.11.1 LTS BUILD 3
 - Client version 1.8.9 Forge+Optifine+LiteLoader
 - Other version Sprac 3.7.0

**Other plugins**
StrikeTab, ImanityPracticeAddon, ViaVersion, ViaRewind, ViaRewind-legacy-support, ...

**Additional context**
I think /battlekit deathcountdown <kitName> can like this:

/battlekit deathcountdown <kitName> <time>
when time set to 0/-1, death no countdown
when time set to other integer, it has custom countdown

**Comment by toppev** [comment]
Did I understand this correctly:
"coundown-go" message is sent even though it's set to '' or 'false'? The messages are same for all countdowns (game start & respawn).

The /battlekit deathcountdown does not directly affect whether that message is sent. It only affects whether there is the countdown (4,3,2,1, go) after you die in bedwars. If you don't want the countdown when you respawn in bedwars, the /battlekit deathcountdown should be set to false (not that in the kits.yml the option is called "no-death-countdown" and the opposite value of  /battlekit info's "death countdown" is stored in it so don't be confused by that in the kits.yml)

**Comment by Yurinann** [comment]
> Did I understand this correctly: "coundown-go" message is sent even though it's set to '' or 'false'? The messages are same for all countdowns (game start & respawn).
> 
> The /battlekit deathcountdown does not directly affect whether that message is sent. It only affects whether there is the countdown (4,3,2,1, go) after you die in bedwars. If you don't want the countdown when you respawn in bedwars, the /battlekit deathcountdown should be set to false (not that in the kits.yml the option is called "no-death-countdown" and the opposite value of /battlekit info's "death countdown" is stored in it so don't be confused by that in the kits.yml)

In fact, even though `no-death-countdown` is set to `true`, there will still be no countdown for death respawns.

Also, `countdown-go` will only be sent repeatedly in this mode.

**Comment by toppev** [comment]
> > Did I understand this correctly: "coundown-go" message is sent even though it's set to '' or 'false'? The messages are same for all countdowns (game start & respawn).
> > The /battlekit deathcountdown does not directly affect whether that message is sent. It only affects whether there is the countdown (4,3,2,1, go) after you die in bedwars. If you don't want the countdown when you respawn in bedwars, the /battlekit deathcountdown should be set to false (not that in the kits.yml the option is called "no-death-countdown" and the opposite value of /battlekit info's "death countdown" is stored in it so don't be confused by that in the kits.yml)
> 
> In fact, even though `no-death-countdown` is set to `true`, there will still be no countdown for death respawns.
> 
> Also, `countdown-go` will only be sent repeatedly in this mode.

`no-death-countdown: true` means there is no countdown for death respawns so it works as expected(?) Are you really sure there are no other errors and it's not anything specific to your setup? Otherwise, I'll need to wait if more people report this as I have not seen this before and not able to reproduce.

**Comment by Yurinann** [comment]
> > > Did I understand this correctly: "coundown-go" message is sent even though it's set to '' or 'false'? The messages are same for all countdowns (game start & respawn).
> > > The /battlekit deathcountdown does not directly affect whether that message is sent. It only affects whether there is the countdown (4,3,2,1, go) after you die in bedwars. If you don't want the countdown when you respawn in bedwars, the /battlekit deathcountdown should be set to false (not that in the kits.yml the option is called "no-death-countdown" and the opposite value of /battlekit info's "death countdown" is stored in it so don't be confused by that in the kits.yml)
> > 
> > 
> > In fact, even though `no-death-countdown` is set to `true`, there will still be no countdown for death respawns.
> > Also, `countdown-go` will only be sent repeatedly in this mode.
> 
> `no-death-countdown: true` means there is no countdown for death respawns so it works as expected(?) Are you really sure there are no other errors and it's not anything specific to your setup? Otherwise, I'll need to wait if more people report this as I have not seen this before and not able to reproduce.

There isn't have any other errors. I will try to reproduce it on a new and clean environment.
And is this setting influenced by some other settings like kit name? (my kit name is `rushbed`)
