### ISSUE TITLE
[Enhancement] Placeholder Enhance

### ISSUE THREAD

**Issue by Yurinann** [toppev/strikepractice-public#15]
**Is your feature request related to a problem? Please describe.**
when I set my countdown-go message to this:
```
  countdown-go: |
    \n
    &8&m----------------------------
    &b&lReunion &8| &f<kit>
    \n
    &7Opponent &f<opponent> &8| &7Map &f<arena>
    \n
    &b&l战斗开始!
    &8&m----------------------------\n
```

in normal 1v1 mode, it is like this:
```
    ----------------------------
    Reunion | NoDebuff

    Opponent Yurinann | Map Arena1

    战斗开始!
    ----------------------------
```

but in party 2v2 mode, it is like this:
```
    ----------------------------
    Reunion | NoDebuff
    
    Opponent -- | Map Arena1

    战斗开始!
    ----------------------------
```

and in event(like KOTH), it is like this:
```
    ----------------------------
    Reunion | NoDebuff
    
    Opponent -- | Map <invalid>

    战斗开始!
    ----------------------------
```

**Describe the solution you'd like**
It's my own purpose and should not be used together

1. can there have a global placeholder? (return party/event all members' name)
2. can there have there own message set?
3. ...

**Describe alternatives you've considered**
there isn't have other solution.. and the default message of party start <opponent> is also return `--`

**Additional context**
none

**Comment by toppev** [comment]
somehow missed this issue, should be fixed in next update
