### ISSUE TITLE
[BUG] Brackets event kits

### ISSUE THREAD

**Issue by imdauts** [toppev/strikepractice-public#18]
**Describe the bug** VERSION 3.7.2-SNAPSHOT (latest at time of posting)
Selecting a kit, in this case "OneHit" will always revert to nodebuff even when the permission is set to true. Some other donators will occasionally 

**To Reproduce**
1. Host a brackets event through the selector or /hostevent brackets 
2. Select another kit other than Nodebuff with the permission node strikepractice.hostevent.brackets set to true.
3. You can see that event kit is still nodebuff.

me testing the issue on a donator account:
video: https://streamable.com/mk5bpb

my donator having the issue:
https://imgur.com/a/ky7iitj

**Expected behavior**
The event uses the selected kit from the user.

**Screenshots**
Permission for the rank hosting the event https://i.imgur.com/9Da5PG8.png
Inherited permission node from the previous rank https://i.imgur.com/fy9dfx8.png 

**Errors and console logs**
**Event starting with debug mode enabled & an error** https://pastebin.com/cKTkAMK3

**Checklist**
- [✔️] The issue occurs on latest version of StrikePractice.
- [❓] I am running a server with ~ 70 players (at time of recording) and after testing it once on my localhost the issue didn't occur. Keep in mind that sometimes this event may randomly decides to work for some donators. I'm sorry I did not test this extensively on a localhost, but I don't have something that should drastically affect this. **Please contact me on discord (dauts#0844) if you don't think this issue is caused by strikepractice and we can investigate from there.**
- [❌] I am using regular spigot or paper (not a fork) and the issue still occurs. I use PandaSpigot, everything has worked so far so I doubt this is the cause of the issue.
- [✔️] I have purchased StrikePractice or I am working with someone who has purchased the resource. 

**Versions:**
 - Server version: Panda Spigot 1.8.8
 - Client version Lunar Client & Vanilla
 - Please contact dauts#0844 for details related to plugins.

**Other plugins**
 Please contact dauts#0844 for details related to plugins.

**Comment by toppev** [comment]
Does this happen when the event "auto-starts" due to enough players.
There seems to be a bug in that case.
Basically, when "brackets.auto-start" players join, it will start in "brackets.auto-start-after-seconds" seconds. This is pretty much a legacy feature before /hostevent /events were added, I'll fix that but as a workaround, you can set

```yaml
# in config.yml
brackets:
  auto-start: 999
```

**Comment by toppev** [comment]
should be fixed nowadays
