### ISSUE TITLE
[BUG] Theft of items from the kit editor

### ISSUE THREAD

**Issue by EneRGO22** [toppev/strikepractice-public#2]
**Describe the bug**
The inertia cheat has an xcarry function that allows you to put items in a crafting slot in your inventory and use these slots as additional ones. So. The player takes these things from the whale editor. Lies in these crafting slots and teleports to spawn and can pick up these things from these slots and use them at spawn!

**To Reproduce**
1. Download cheat Interia
2. Enable xcarry function
3. Enter whale editing mode
4. Take the item and put it in the layout slot in the inventory
5. Teleport to spawn and you can get from there those things that you put in edit mode

**Screenshots**
![image](https://user-images.githubusercontent.com/68811273/160192700-33a94a69-a27d-4445-a3a9-b9bd4db395f6.png)
![image](https://user-images.githubusercontent.com/68811273/160192721-86235ae3-8cf2-4bbe-af25-0dd13ecb7bac.png)
![image](https://user-images.githubusercontent.com/68811273/160192736-d8409739-d24e-44aa-88cb-81fe7d4b8108.png)

**Checklist**
- [x] The issue occurs on latest version of StrikePractice.
- [x] The issue occurs without other plugins (or non-official addons).
- [x] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [x] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:**
 - Server version [![image](https://user-images.githubusercontent.com/68811273/160192934-48cbe798-fdc3-42fe-b702-f02c986b9984.png)]
 - Client version [interia 1.16.5]

**Comment by toppev** [comment]
The plugin does not let the user save other items in a kit which prevents gaining actual advantage from this kind of abuse in fights. Also, as it requires a hacked client, I won't address this any further.

**Comment by EneRGO22** [comment]
I repeat, it does not allow you to save other things in the set. But there is a way to get them and run around the spawn. I have a player running in diamond armor and elytra and hitting players. This is not normal, I don't understand why you don't want to fix this even though it is a BUG!
