### ISSUE TITLE
[BUG] LanguageItems not saving

### ISSUE THREAD

**Issue by siBalda** [toppev/strikepractice-public#25]
**Describe the bug**
LanguageItems not saving

**To Reproduce**
1. Create a language item with /li create language slot
2. Restart the server or even run /sprac savelanguageitems first
3. See that the language item has not been saved

**Expected behavior**
Languageitems changed.

**Versions:**
 - Server version [1.19.4]
 - Client version [Fabric 1.20.1]

**Comment by toppev** [comment]
Fixed in devbuilds now
