### ISSUE TITLE
[BUG] Spectator bug & Arrows not disappearing

### ISSUE THREAD

**Issue by majkefer** [toppev/strikepractice-public#32]
**Describe the bug**
- Spectator can interfere with gameplay in Crystal & Cart PvP. Specifically, they can stand on top of an obsidian block to prevent players from placing Crystals & they can destroy TNT Minecarts.
- Arrows not disappearing after rounds end in a single match with more rounds, but they disappear after the duel is finished.

**To Reproduce**
*Spectator bug*
1. Spectate a duel.
2a. Stand on obsidian. || 2b. Let one of the duelists place a TNT cart.
3a. One of the duelists tries to place crystal where you are standing || 3. Hit the minecart.
4a. They are unable to place it. || 4b. The minecart is broken.

*Arrow bug*
1. Start a duel with bows.
2. Shoots arrows at the ground.
3. End the round.
4. The arrows should still be on the ground in the next round.

**Expected behavior**
We expect arrows on the ground to disappear after each round, not after the entire duel.
Spectators shouldn't be able to interact with the game environment.

**Screenshots**

**Errors and console logs**

**Checklist**
- [x] The issue occurs on latest version of StrikePractice.
- [x] The issue occurs without other plugins (or non-official addons).
- [x] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [x] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:**
 - Server version [1.20.4 Paper Spigot]
 - Client version [1.20.4]
 

**Other plugins**
StrikePractice, StrikeTab, ...

**Additional context**

**Comment by toppev** [comment]
1. You can use spectator gamemode for spectators. In the config.yml, set: `spectator-gamemode: SPECTATOR`

2. In devbuilds the arrows should reset now (between rounds too
