### ISSUE TITLE
[BUG] You can take things from the gui menu

### ISSUE THREAD

**Issue by EneRGO22** [toppev/strikepractice-public#4]
**Describe the bug**
If you open the menu of the whale view GUI by clicking on an item to open the view menu, and then go back, then from the GUI menu you can take things to your inventory

**To Reproduce**
1. I will create a menu, and in the menu create an item so that it opens the whale viewing menu.
2. Open whale view
3. Click on the item to go back
4. You open the menu before this
5. You can click on items and pick them up

**Expected behavior**
When entering the whale viewing menu, and then exiting back, items should not be taken into the menu. This is a bug!

**Proof**
https://youtu.be/_6VB-_7yeio

**Checklist**
- [x] The issue occurs on latest version of StrikePractice.
- [x] The issue occurs without other plugins (or non-official addons).
- [x] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [x] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:** 
 - ![image](https://user-images.githubusercontent.com/68811273/161402874-ef243771-886f-4b8f-b46a-9f111d7a6a52.png)
 - 1.16.5 optifine

**Other plugins**
StrikePractice,.

**Comment by iiAhmedYT** [comment]
Can you please show what StrikePractice version this is

**Comment by EneRGO22** [comment]
![image](https://user-images.githubusercontent.com/68811273/161403004-d282b0a4-f8c3-42d6-adb9-0378fca651b3.png)

**Comment by toppev** [comment]
What plugin are you using for the custom GUI? Have you contacted its developer?
StrikePractice never "uncancels" cancelled inventory click events so it should not directly cause anything like this (I'm not saying it happens without SP but that they do something weird)
