### ISSUE TITLE
[BUG] kit editor and /duel bug

### ISSUE THREAD

**Issue by MrKotex** [toppev/strikepractice-public#6]
1. Send someone duel (/duel [name])
2. Send commend /kiteditor and chose a kit
3. This person should accept the duel
4. And you will have items from lobby not a kit

**Expected behavior**
Give a kit

**Screenshots**
https://www.youtube.com/watch?v=lwezX-2hYDQ

**Checklist**
- [+ ] The issue occurs on latest version of StrikePractice.
- [ +] The issue occurs without other plugins (or non-official addons).
- [ +] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [ +] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:**
 - Server version 1.17.1
 - Client version 1.17.1

**Other plugins**
StrikePractice, StrikeLeaderboards

**Comment by toppev** [comment]
should be fixed in next update
