### ISSUE TITLE
[BUG] PlaceholderAPI Hook issue

### ISSUE THREAD

**Issue by ImYenil** [toppev/strikepractice-public#7]
**Describe the bug**

**To Reproduce**
2. Do '....'
3. Then '....'
4. See that '....' happens

**Expected behavior**

**Screenshots**

**Errors and console logs**
If there are any errors in the console, please include them here.
If there are no errors, enable "/sprac debug" and check if there are any relevant debug logs.

**Checklist**
- [ ] The issue occurs on latest version of StrikePractice.
- [ ] The issue occurs without other plugins (or non-official addons).
- [ ] I am using regular spigot or paper (not a fork) and the issue still occurs.
- [ ] I have purchased StrikePractice or I am working with someone who has purchased the resource.

**Versions:**
 - Server version [e.g. 1.8.8 spigot
 - Client version [e.g. Lunar Client 1.8.9
 - Other version [e.g. Database, addons, plugins]

**Other plugins**
StrikePractice, StrikeTab, ...

**Additional context**
https://pastebin.com/0Dj84Kr7

**Comment by toppev** [comment]
<arena> placeholder cannot be used at spawn, for example and you are trying to do something similar
